### ISSUE TITLE
Error in Readme ?

### ISSUE THREAD

**Issue by mysther** [tomMoulard/htransformation#38]
Hello, in readme file you have the following example : 

```yml
#Example
- Rule:
  Name: 'Header addition'
  Header: 'X-Custom-2'
  Value: 'True'
  Type: 'Set'
- Rule:
  Name: 'Header deletion'
  Header: 'X-Custom-2'
  Type: 'Del'
- Rule:
  Name: 'Header join'
  Header: 'X-Custom-2'
  Value: 'False'
  Type: 'Set'
```
But in doesn't work at all ...

The following code works :
```yml
Rules:
  - Name: "Rewrite to http"
    Type: "RewriteValueRule"
    Header: "Destination"
    Value: "https://(.*)"
    ValueReplace: "http://$1"
```
Am I the only one in this case? Am I missing something?

I searched for four hours why I couldn't get the plugin to work due to this  :')
