### ISSUE TITLE
Typo in Readme?

### ISSUE THREAD

**Issue by michvllni** [tomMoulard/htransformation#40]
In the readme the example for Set has the type Join:

```yaml
# Example Join
- Rule:
      Name: 'Set Cache-Control'
      Header: 'Cache-Control'
      Value: 'Foo'
      Type: 'Join'
```

Is this intentional?
I would propose a fix myself but I don't know the desired Example you wanted to have here
