### ISSUE TITLE
README.md documentation for join incorrect and scenario proposal.

### ISSUE THREAD

**Issue by sergioa** [tomMoulard/htransformation#46]
Hi,

According to the documentation for Join manipulation (https://github.com/tomMoulard/htransformation#join).

````yaml
# Example Usage
- Rule:
  Name: 'Header set'
  Header: 'X-Forwarded-For'
  HeaderPrefix: "^"
  Values:
      - 'Foo'
      - '^CF-Connecting-IP'
  Type: 'Join'
````

will result in:

````yaml
# Old header:
X-Forwarded-For: 1.1.1.1
CF-Connecting-IP: 2.2.2.2
# New headers:
CF-Connecting-IP: 2.2.2.2
X-Forwarded-For: Foo, 1.1.1.1
````

But I guess that's not the case.

Wouldn't it be?

````yaml
# Old header:
X-Forwarded-For: 1.1.1.1
CF-Connecting-IP: 2.2.2.2
# New headers:
CF-Connecting-IP: 2.2.2.2
X-Forwarded-For: 1.1.1.1,Foo,2.2.2.2
````

Actually, I would like to allow Join not to only append but also to prepend.

As a more generic scenario.

````yaml
# Example Usage
- Rule:
  Name: 'Header set'
  Header: 'X-Forwarded-For'
  HeaderPrefix: "^"
  Values:
      - '^CF-Connecting-IP'
      - '^X-Forwarded-For'
  Type: 'Join'
````

````yaml
# Old header:
X-Forwarded-For: 1.1.1.1
CF-Connecting-IP: 2.2.2.2
# New headers:
CF-Connecting-IP: 2.2.2.2
X-Forwarded-For: 2.2.2.2,1.1.1.1
````

The value of `Header` will be overridden by the resulting concatenation of `Values` elements or, if `Header` does not exist, it will be automatically created and populated with the same concatenation.

As this might be breaking backwards compatibility a new `Type` may be defined.

What do you think?

**Comment by tomMoulard** [comment]
Hello @sergioa,

Thanks for your interest in this Traefik Plugin !

Indeed, there is an error in the README, and I have fixed it in the newest PR.

As for the prepending, I think it is not a good idea to change the configuration for the join header manipulation system.
I would rather use this workaround:
```yaml
- Rule:
  Name: "defining a tmp header to store the Xff value in."
  Header: 'Xff'
  value: 'Xff-tmp'
  Type: 'Rename'
- Rule:
  Name: "Setting the Xff header value."
  Header: 'Xff'
  Value: '2.2.2.2'
  Type: 'Set'
- Rule:
  Name: "Appending the previous XFF header value after the new value."
  Header: 'Xff'
  HeaderPrefix: "^"
  Sep: ','
  Values:
      - '^Xff-tmp'
  Type: 'Join'
- Rule:
  Name: "Deleting the tmp header."
  Header: 'Xff-tmp'
  Type: 'Del'
```
