### ISSUE TITLE
SetOnResponse with RewriteValueRule v0.2.7 doesn't work

### ISSUE THREAD

**Issue by kanchev1** [tomMoulard/htransformation#50]
Hi,

Thanks for your work on this great plugin, it'd be amazing if the response header manipulation works!

I have a simple rule to remove the Secure flag of a cookie:
```yaml
            - Rule:
              Name: 'Unsecure Cookie'
              Header: 'Set-Cookie'
              Value: '(.*)Secure(.*)'
              ValueReplace: 'BABLA-$1-$2'
              Type: 'RewriteValueRule'
              SetOnResponse: true
```
This is simply a basic test rule to check if it's working at all. The cookies in the response are unchanged.

The plugin actually works on my configuration since I also Set some request headers.

I'm using traefik 2.10.4.

UPDATE: The following plugin seems to be the only one able to modify the response headers correctly: https://github.com/XciD/traefik-plugin-rewrite-headers
