### ISSUE TITLE
kubernetes example

### ISSUE THREAD

**Issue by isshwar** [tomMoulard/htransformation#56]
Hi,

If someone had already worked on it, how to enable the plugin and then write the rule when deploying traefik on kubernetes.

Thanks in advance

**Comment by tomMoulard** [comment]
Hi @isshwar,

Thanks for your interest in this Traefik Plugin!

As per [this>install this Plugin](https://plugins.traefik.io/plugins/62947319108ecc83915d7789/header-transformation):

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: my-htransformation
    namespace: my-namespace
spec:
    plugin:
        htransformation:
            Rules:
                - Header: X-Traefik-*
                  Name: Header transformation
                  Type: Rename
                  Value: X-custom
                - Header: NewHeader
                  Name: Header addition
                  Type: Set
                  Value: "True"
                - Header: Cache-Control
                  Name: Header deletion
                  Type: Del
                - Header: Accept-Language
                  Name: Header join
                  Sep: ', '
                  Type: Join
                  Values:
                    - Foo
                    - Bar

```
